services:
  postgres:
    image: postgres:alpine3.16
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  migrate:
    image: migrate/migrate:v4.15.2
    command:
      - -path=/migrations/
      - -database=postgres://postgres:password@postgres:5432/postgres?sslmode=disable
      - up
    #      - down
    #      - -all
    restart: on-failure
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres

volumes:
  pgdata: